article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addarticle/', views.addArticle, name="addarticle"),
    path('article/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.updateArticle, name="update"),
    path('delete/<int:id>', views.deleteArticle, name="delete"),
    path('', views.articles, name="articles"),
    path('comment/<int:id>', views.addComment, name="comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE, verbose_name="Yazar")
    title = models.CharField(max_length=50, verbose_name="Başlık")
    content = RichTextField(verbose_name="İçerik")
    created_date = models.DateTimeField(auto_now_add = True, verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank=True,null=True,verbose_name="Makaleye fotoğraf/dosya ekleyin")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ["-created_date"]

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE, verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name="İsim")
    comment_content = models.CharField(max_length=200, verbose_name="Yazar")
    comment_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.comment_author
    class Meta:
        ordering = ["-comment_date"]

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

user/forms.py
from typing import Any
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label="Parola",widget=forms.PasswordInput)



class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label="Kullanıcı Adı")
    password = forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label="Parolayı Doğrula",widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar eşleşmiyor")
        values = {
            "username":username,
            "password":password,
        }
        return values

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
from .models import Article, Comment
from django.contrib import messages
from django.db.models import Count

# Create your views here.


def articles(request):

    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": articles})

    articles = Article.objects.all()

    return render(request, "articles.html", {"articles": articles})


def index(request):
    most_commented_articles = Comment.objects.values('article_id').annotate(
        comment_count=Count('id')).order_by('-comment_count')[:10]
    most_commented_article_ids = [
        str(article_id_list['article_id']) for article_id_list in most_commented_articles]
    articles = []
    for i in most_commented_article_ids:
        articles += Article.objects.filter(id=i)

    latest_articles = Article.objects.order_by('-created_date')[:10]

    context = {"articles": articles, "most_commented_articles":
               most_commented_articles, "latest_articles": latest_articles}

    return render(request, "index.html", context)


def about(request):
    return render(request, "about.html")


@login_required(login_url="user:login")
def dashboard(request):

    articles = Article.objects.filter(author=request.user)

    context = {
        "articles": articles
    }

    return render(request, "dashboard.html", context)


@login_required(login_url="user:login")
def addArticle(request):

    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():

        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, "Makale Başarıyla Oluşturuldu")
        return redirect("article:dashboard")

    return render(request, "addarticle.html", {"form": form})


def detail(request, id):

    article = get_object_or_404(Article, id=id)

    comments = article.comments.all()

    return render(request, "detail.html", {"article": article, "comments": comments})


@login_required(login_url="user:login")
def updateArticle(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None,
                       request.FILES or None, instance=article)

    if form.is_valid():

        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, "Makale Başarıyla Güncellendi")
        return redirect("article:dashboard")

    return render(request, "update.html", {"form": form})


@login_required(login_url="user:login")
def deleteArticle(request, id):

    article = get_object_or_404(Article, id=id)

    article.delete()

    messages.success(request, "Makale Başarıyla Silindi")
    return redirect("article:dashboard")


def addComment(request, id):
    article = get_object_or_404(Article, id=id)

    if request.method == "POST":
        comment_author = request.user
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author=comment_author,
                             comment_content=comment_content)

        newComment.article = article

        newComment.save()

        return redirect(reverse("article:detail", kwargs={"id": id}))

    pass

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from .forms import RegisterForm,LoginForm

# Create your views here.

def register(request):
    form = RegisterForm(request.POST or None)
    
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username=username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.success(request,"Başarıyla Kayıt Oldunuz")

        return redirect("index")
    context = {
        "form": form
    }
    return render(request,"register.html",context)

def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username=username,password=password)

        if user is None:
            messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context)
        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)

def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}

{% block body %}

<h3> Hakkımızda </h3>
<hr>

<p>Yazılım Bloğu</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3> Makale Oluştur</h3>
        <hr>
        
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
        <button type="submit" class="btn btn-success">Makale Paylaş</button>
        </form>

    </div>
  </div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <h3>Makaleler</h3>
            <hr>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
<form>
    {% csrf_token %}
    <input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Ara...">
    <button type="submit" class="btn btn-danger">Ara</button>
</form>
<hr>
</div>
</div>
</div>
{% if articles %}
{% for article in articles %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <a href="{% url 'article:detail' article.id %}"><h1
                            class="fw-bolder mb-1">{{article.title}}</h1></a>
                    <!-- Post meta content-->
                    <div
                        class="text-muted fst-italic mb-2"><b>{{article.created_date}}</b>
                        tarihinde <b>{{article.author.username}}</b> tarafından
                        yayınlanmıştır</div>
                </header>
                <!-- Preview image figure-->
                {% if article.article_image %}
                <a href="{% url 'article:detail' article.id %}"><figure
                        class="mb-4"><img class="img-fluid rounded"
                            src="{{article.article_image.url}}"
                            alt="..." /></figure></a>
                {% endif %}

                <!-- Post content-->
                <section class="mb-5">
                    {{article.content|safe|truncatewords:50}}
                </section>
                <a style="float : right" href="{% url 'article:detail' article.id %}"
                    class="btn btn-info">Devamını Oku</a>
            </article>
        </div>
    </div>
</div>
<hr>
{% endfor %}

{% else %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
<div class="alert alert-danger">Makale Bulunamadı</div>
</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3>Kontrol Paneli</h3>
<hr>

<p>Hoşgeldiniz, <small>{{request.user.username}}</small></p>
<hr>
<a class="btn btn-info" href="{% url 'article:addarticle' %}">Makale Ekle</a>
<hr>
{% if articles %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
        {% for article in articles %}
            <tr>
                <th scope="row">{{article.id}}</th>
                <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                <td>{{article.author.username}}</td>
                <td>{{article.created_date}}</td>
                <td><a href="{% url 'article:update' article.id %}" class="btn btn-warning">Güncelle</a></td>
                <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
            </tr>
        
        {% endfor %}


    </tbody>
  </table>
{% else %}
<div class="alert alert-danger">Henüz Makaleniz Bulunmuyor</div>
{% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %} {% block body %}

<div class="row">
  <div class="col-lg-8">
    <!-- Post content-->
    <article>
      <!-- Post header-->
      <header class="mb-4">
        <!-- Post title-->
        <h1 class="fw-bolder mb-1">{{article.title}}</h1>
        <!-- Post meta content-->
        <div class="text-muted fst-italic mb-2">
          <b>{{article.created_date}}</b> tarihinde
          <b>{{article.author.username}}</b> tarafından yayınlanmıştır
        </div>
      </header>
      <!-- Preview image figure-->
      {% if article.article_image %}
      <figure class="mb-4">
        <img
          class="img-fluid rounded"
          src="{{article.article_image.url}}"
          alt="..."
        />
      </figure>
      {% endif %}

      <!-- Post content-->
      <section class="mb-5">{{article.content|safe}}</section>
    </article>

    <!-- Comments section-->
    <section class="mb-5">
      <div class="card bg-light">
        <div class="card-body">
          {% if comments %} {% for comment in comments %}
          <div class="d-flex">
            <div class="flex-shrink-0">
              <img
                class="rounded-circle"
                src="https://dummyimage.com/50x50/ced4da/6c757d.jpg"
                alt="..."
              />
            </div>
            <div class="ms-3">
              <div class="fw-bold">{{comment.comment_author}}</div>
              <div class="text-muted fst-italic mb-2">
                <b>{{comment.comment_date}}</b>
              </div>
              {{comment.comment_content}}
            </div>
          </div>
          <hr>
          {% endfor %} {% else %}
          <div class="alert alert-primary">Henüz Yorum Bulunmuyor</div>
          {% endif %}

          <!-- Comment form-->
          <form
            class="mb-4"
            method="post"
            action="{% url 'article:comment' article.id%}"
          >
            {% csrf_token %}
            <textarea style="margin-top: 10px"
              name="comment_content"
              class="form-control"
              rows="3"
              placeholder="Yorum Yaz..."
            ></textarea>
            <button
              style="margin-top: 10px"
              type="submit"
              class="btn btn-primary"
            >
              Gönder
            </button>
          </form>
        </div>
      </div>
    </section>
  </div>
</div>

{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">MFT Blog</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Hakkımızda</a>
        </li>
  
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ms-auto">

        {% if request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
          </li>
        {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
          </li>
        {% endif %}



      </ul>
    </div>
  </nav>
  

templates/includes/posttemplate.html
<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">Posted on January 1, 2023 by Start Bootstrap</div>
                <!-- Post categories-->
                <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
            </header>
            <!-- Preview image figure-->
            <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
            </section>
        </article>
    </div>
</div>

templates/index.html
{% extends "layout.html" %} 

{% block body %}

<div class="jumbotron text-center">
  <h3>Yazılım Bloğuna Hoş Geldiniz</h3>
  <p>
    Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz.
  </p>

</div>
<hr>
<div class="row">
  <div class="col-md-10 offset-mr-3">
    <div class="row">
      <div class="col-lg-5" id="most_commented">
          <h3>En Çok Yorum Alanlar</h3>
          <hr>
          
          <ul class="list-group">
            {% if articles %} {% for article_infos in articles %}
          
            <a href="{% url 'article:detail' article_infos.id %}" >
              <li class="list-group-item d-flex justify-content-between align-items-center">
                {{article_infos.title}}
                <span class="badge bg-primary rounded-pill">
                  {% for article_queryset in most_commented_articles %}

                  {% if article_infos.id == article_queryset.article_id %}

                  {{article_queryset.comment_count}}

                  {{break}}
                  {% else %}
                  {% endif %}
                  
                  {% endfor %}
                </span>
              </li>
            </a>
          
          
            <hr>
            {% endfor %} {% else %}
            <div class="alert alert-primary">Henüz Yorum Bulunmuyor</div>
            {% endif %}
          
          

          </ul>
      </div>
      <div class="col-lg-5" id="latest_article">
        <h3>En Son Eklenenler</h3>
        <hr>
        
        <ul class="list-group">
          {% if latest_articles %} {% for latest_article in latest_articles %}
        
          <a href="{% url 'article:detail' latest_article.id %}" >
            <li class="list-group-item d-flex justify-content-between align-items-center">
              {{latest_article.title}}

            </li>
          </a>
        
        
          <hr>
          {% endfor %} {% else %}
          <div class="alert alert-primary">Henüz Yorum Bulunmuyor</div>
          {% endif %}
        
        

        </ul>
    </div>
  </div>
  </div>
</div>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="../static/style.css">
    <title>Blog</title>
</head>
<body>
    {% include "includes/navbar.html" %}



    <div style="margin-top:100px; margin-bottom:50px;" class="container">

        {% if messages %}
        {% for message in messages %}
        {% if message.tags == "info" %}
            <div class="alert alert-danger">{{ message }}</div>
        {% else %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
        
        {% endfor %}
        {% endif %}

        {% block body %}
        
        {% endblock body %}

    </div>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}


{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3> Giriş Yap</h3>
        <hr>
        
        <form method="post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
        <button type="submit" class="btn btn-danger">Giriş Yap</button>
        </form>

    </div>
  </div>




{% endblock body %}

templates/logout.html
{% extends "layout.html" %}

{% block body %}

<h3> Çıkış Yap</h3>
<hr>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3> Kayıt Ol</h3>
    <hr>

    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
    <button type="submit" class="btn btn-danger">Kayıt Ol</button>
    </form>

</div>
</div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3> Makale Güncelle</h3>
        <hr>
        
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
        <button type="submit" class="btn btn-success">Makale Güncelle</button>
        </form>

    </div>
  </div>

{% endblock body %}